# Generated by Django 4.1.2 on 2022-10-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
