# Generated by Django 4.1.2 on 2022-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fb_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='insta_link',
            field=models.URLField(max_length=255),
        ),
    ]
