# Generated by Django 4.1.2 on 2022-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_team_fb_link_alter_team_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
